baseURL = 'https://www.meowlang.cn/'
languageCode = 'zh-cn'
title = '我的好物推广小站'
theme = 'PaperMod'
pagination.pagerSize = 10
enableRobotsTXT = true

[params]
  homeInfoParams = { Title = "欢迎来到我的推广世界", Content = "精选好物，推荐给您！" }
  ShowReadingTime = true
  ShowShareButtons = true
  defaultTheme = "auto"

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "产品推荐"
  url = "/products/"
  weight = 1

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 2
